### PR TITLE
Added option to persist exposed images

### PR DESCRIPTION
**Pull request by rsteckler**
This creates an option for

```
expose_images_persist: true
```

in the service configuration. When true, it prepends the images stored in /config/www/llmvision with the frigate event ID. The prevents them from being overwritten the next time the service runs.

### CODE REVIEW

**Comment by valentinfrlch** [comment]
Great idea. Not sure, but I think we could turn the existing `expose_images` into a 'select' selector (instead of boolean) with options ["Don't expose", "Expose temporarily", "Expose indefinitely"]. This way there isn't a new input. Wouldn't be backward compatible though.

**Comment by rsteckler** [comment]
> Great idea. Not sure, but I think we could turn the existing `expose_images` into a 'select' selector (instead of boolean) with options ["Don't expose", "Expose temporarily", "Expose indefinitely"]. This way there isn't a new input. Wouldn't be backward compatible though.

Totally - breaking change though and you're exposing everyone to the advanced option.  The other pitfall in bringing them together into a single parameter is that every casual user needs to make a choice of whether to persist them or not, which means they need to understand how the various forms of persistence work.  
The nice thing about keeping the options separate is that you can just have expose_images as a true/false in the blueprint and casual users will never need to understand the difference between persist/ephemeral.  But when you run into an expert user who doesn't like the ephemeral default, they can just go add a param to the service call and solve their problem.

Really six of one, half-dozen of another, so either way works.  The breaking change leads me to think the separate vars are a better option, but even then you could have the service code handle both, have the blueprint only expose the new way, and mark it for future deprecation to give people time to change it.

**Comment by valentinfrlch** [comment]
You're right, separate options it is. Breaking changes ain't it. I'll take a look at this (and the other 2 PRs) after next week. Thanks for the patience!

**Comment by rsteckler** [comment]
Resolved the conflicts, so this is ready to merge if you'd like.

**Pull request merged**
